version: '3.7'

services:
  mongo:
    container_name: mongo
    image: mongo:4.2.6
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - bootcamp:/data/db

  mongo-express:
    image: mongo-express
    container_name: mongo_express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example

  redis:
    image: redis:6.0.3
    container_name: redis
    ports:
      - 6379:6379

volumes:
  bootcamp: